version: '3.7'
services:
  nameserver:
    image: pyro5/ns
    ports:
      - "9090:9090"

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - nameserver
    environment:
      - PYRO_HOST=server

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    stdin_open: true
    tty: true